# Generated by Django 6.0.2 on 2026-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discorduser',
            options={'verbose_name': 'Discordユーザー', 'verbose_name_plural': 'Discordユーザー一覧'},
        ),
        migrations.AlterModelOptions(
            name='oversleptresult',
            options={'verbose_name': '寝坊結果', 'verbose_name_plural': '寝坊結果一覧'},
        ),
        migrations.AlterModelOptions(
            name='predictionresult',
            options={'verbose_name': '予測結果', 'verbose_name_plural': '予測結果一覧'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'verbose_name': 'クイズ結果', 'verbose_name_plural': 'クイズ結果一覧'},
        ),
        migrations.AlterField(
            model_name='oversleptresult',
            name='overslept_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
    ]
