# Generated by Django 6.0.2 on 2026-02-17 02:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordapp', '0002_alter_discorduser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guild_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('members', models.ManyToManyField(related_name='guilds', to='discordapp.discorduser')),
            ],
            options={
                'verbose_name': 'Discordギルド',
                'verbose_name_plural': 'Discordギルド一覧',
            },
        ),
    ]
