# Generated by Django 6.0.2 on 2026-02-18 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordapp', '0004_bluffnumberresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('play_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordapp.discorduser')),
            ],
            options={
                'verbose_name': 'フラッシュ結果',
                'verbose_name_plural': 'フラッシュ結果一覧',
            },
        ),
    ]
